# numpy.arange()
NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory

In [2]:
import numpy as np
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [3]:
# Python Programming illustrating 
# numpy.arange method 
  
import numpy as np
  
print("A\n", np.arange(4).reshape(2, 2), "\n") 
  
print("A\n", np.arange(4, 10), "\n") 
  
print("A\n", np.arange(4, 20, 3), "\n") 

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



# numpy.reshape()

In [4]:
# Python Program illustrating 
# numpy.reshape() method 
  
import numpy as np 
  
array = np.arange(8) 
print("Original array : \n", array) 
  
# shape array with 2 rows and 4 columns 
array = np.arange(8).reshape(2, 4) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 
  
# shape array with 2 rows and 4 columns 
array = np.arange(8).reshape(4 ,2) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 
  
# Constructs 3D array 
array = np.arange(8).reshape(2, 2, 2) 
print("\nOriginal array reshaped to 3D : \n", array) 

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [5]:
%time for _ in range(10): my_arr2 = array * 2

Wall time: 0 ns


# numpy.random.randn()

### randomly constructing 1D array

In [6]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 1D Array 
array = np.random.randn(5) 
print("1D Array filled with random values : \n", array); 


1D Array filled with random values : 
 [1.80291739 1.72901932 1.17037828 1.4083274  0.16327289]


### randomly constructing 2D array

In [7]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 2D Array    
array = np.random.randn(3, 4) 
print("2D Array filled with random values : \n", array);

2D Array filled with random values : 
 [[ 0.50752452 -1.58250975 -0.38581262  0.77870242]
 [-1.36277558  0.37970064  1.33778426  1.53023782]
 [-0.65374959  0.88320417 -0.85785219  1.24657268]]


### randomly constructing 3D array

In [8]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 3D Array      
array = np.random.randn(2, 2 ,2) 
print("3D Array filled with random values : \n", array);

3D Array filled with random values : 
 [[[ 2.66631739 -0.79747539]
  [ 0.81389981  0.62765011]]

 [[ 1.48138319  0.6967646 ]
  [ 1.57983278  0.67575059]]]


In [9]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 3D Array      
array = np.random.randn(2, 2 ,2) 
print("3D Array filled with random values : \n", array); 
       
# Multiplying values with 3 
print("\nArray * 3 : \n", array *3) 

# Multiplying values with 3 + 2
print("\nArray * 3 + 2 : \n", array *3 + 2) 
  
# Or we cab directly do so by  
array = np.random.randn(2, 2 ,2) * 3 + 2
print("\nArray * 3 + 2 : \n", array); 


3D Array filled with random values : 
 [[[ 0.79062299 -0.8130796 ]
  [-1.47446788 -1.33576403]]

 [[-0.60738044  0.73579137]
  [-1.02665738  1.32276961]]]

Array * 3 : 
 [[[ 2.37186896 -2.4392388 ]
  [-4.42340363 -4.0072921 ]]

 [[-1.82214133  2.20737412]
  [-3.07997213  3.96830883]]]

Array * 3 + 2 : 
 [[[ 4.37186896 -0.4392388 ]
  [-2.42340363 -2.0072921 ]]

 [[ 0.17785867  4.20737412]
  [-1.07997213  5.96830883]]]

Array * 3 + 2 : 
 [[[ 8.73217202  2.86605379]
  [ 3.40260768  1.07268269]]

 [[ 2.79470096 -2.00053861]
  [-1.11946582  1.90453241]]]


# Creating ndarrays

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
#print(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# Python program for
# Creation of Arrays
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


### .ndim

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.ndim)

2


### .shape

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.shape)

(2, 4)


### .dtype

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.dtype)

int32


# numpy.zeros()

In [16]:
arr =  np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
arr = np.zeros((3, 6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
import numpy as geek 
  
b = np.zeros(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.zeros([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.zeros([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Python Program illustrating 
# numpy.zeros method 
  
import numpy as np 
  
# manipulation with data-types 
b = np.zeros(2, dtype=[('x', 'float'), ('y', 'int'),("z","complex")]) 
print(b)

[(0., 0, 0.+0.j) (0., 0, 0.+0.j)]


# numpy.empty()
It’s not safe to assume that np.empty will return an array of all
zeros. In some cases, it may return uninitialized “garbage” values.

In [20]:
# Python Programming illustrating 
# numpy.empty method 
  
import numpy as np 
  
b = np.empty(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.empty([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.empty([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# numpy.ones()

In [21]:
# numpy.ones method 
  
import numpy as np
  
b = np.ones(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.ones([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.ones([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# numpy.eye()

In [22]:
import numpy as np 
  
# 2x2 matrix with 1's on main diagnol 
b = np.eye(2, dtype = float) 
print("Matrix b : \n", b) 
  
# matrix with R=4 C=5 and 1 on diagnol 
# below main diagnol 
a = np.eye(4, 5, k = -1) 
print("\nMatrix a : \n", a)

Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# numpy.identity() in Python

In [23]:
import numpy as np 
  
# 2x2 matrix with 1's on main diagnol 
b = np.identity(2, dtype = float) 
print("Matrix b : \n", b) 
  
  
a = np.identity(4) 
print("\nMatrix a : \n", a) 

Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# NumPy data types

In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [25]:
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

float64


In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)
print(arr)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


# Arithmetic with NumPy Arrays

In [27]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [28]:
print(arr * arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [29]:
print(arr - arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
print(1 / arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [31]:
print(arr ** 0.5)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [32]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [33]:
print( arr2 > arr)

[[False  True False]
 [ True False  True]]


In [34]:
print(arr > arr2)

[[ True False  True]
 [False  True False]]


# Basic Indexing and Slicing

In [35]:
 arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [36]:
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


Now, when I change values in arr_slice, the mutations are reflected in the original array arr:

In [37]:
arr_slice[1] = 12345
print(arr_slice)

[   12 12345    12]


In [38]:
 print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


In [39]:
 arr_slice[:] = 64
print(arr)

[ 0  1  2  3  4 64 64 64  8  9]


In [40]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])

[7 8 9]


In [41]:
arr2d[0][2]

3

In [42]:
 arr2d[0, 2]

3

In [43]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [44]:
arr3d.shape

(2, 2, 3)

In [45]:
arr3d.ndim

3

In [46]:
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


In [47]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [48]:
arr3d[0] = old_values
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [49]:
 arr3d[1, 0]

array([7, 8, 9])

In [50]:
x = arr3d[1]
print(x)

[[ 7  8  9]
 [10 11 12]]


In [51]:
x[0]

array([7, 8, 9])

# Indexing with slices

In [52]:
arr = np.array([ 0, 1, 2, 3, 4, 64, 64, 64, 8, 9])

In [53]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [54]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [57]:
arr2d[1, :2]

array([4, 5])

In [58]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [59]:
 arr2d[:2, 1:] = 0

In [60]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

# Boolean Indexing

In [61]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [62]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [63]:
data

array([[-0.08774042,  1.37997841,  0.50664524, -0.02554547],
       [ 0.08476618, -0.33386197, -0.92602617, -0.11427901],
       [ 0.94329292, -1.04905211, -0.21951467, -0.04858503],
       [ 0.17757912,  1.2114927 ,  1.12016855,  0.18505731],
       [ 2.12477612,  0.49703848,  0.39375899,  1.23850231],
       [ 0.31732413, -0.75535458,  0.36194123, -0.58216024],
       [-1.93996177,  1.97221378,  0.62397917, -0.64372841]])

In [64]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [65]:
data[names == 'Bob']

array([[-0.08774042,  1.37997841,  0.50664524, -0.02554547],
       [ 0.17757912,  1.2114927 ,  1.12016855,  0.18505731]])

In [66]:
data[names == 'Bob', 2:]

array([[ 0.50664524, -0.02554547],
       [ 1.12016855,  0.18505731]])

In [67]:
print(data[names == 'Bob', 3])

[-0.02554547  0.18505731]


In [68]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [69]:
data[~(names == 'Bob')]

array([[ 0.08476618, -0.33386197, -0.92602617, -0.11427901],
       [ 0.94329292, -1.04905211, -0.21951467, -0.04858503],
       [ 2.12477612,  0.49703848,  0.39375899,  1.23850231],
       [ 0.31732413, -0.75535458,  0.36194123, -0.58216024],
       [-1.93996177,  1.97221378,  0.62397917, -0.64372841]])

In [70]:
cond = names == 'Bob'
cond

array([ True, False, False,  True, False, False, False])

In [71]:
data[~cond]

array([[ 0.08476618, -0.33386197, -0.92602617, -0.11427901],
       [ 0.94329292, -1.04905211, -0.21951467, -0.04858503],
       [ 2.12477612,  0.49703848,  0.39375899,  1.23850231],
       [ 0.31732413, -0.75535458,  0.36194123, -0.58216024],
       [-1.93996177,  1.97221378,  0.62397917, -0.64372841]])

In [72]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [73]:
data[mask]

array([[-0.08774042,  1.37997841,  0.50664524, -0.02554547],
       [ 0.94329292, -1.04905211, -0.21951467, -0.04858503],
       [ 0.17757912,  1.2114927 ,  1.12016855,  0.18505731],
       [ 2.12477612,  0.49703848,  0.39375899,  1.23850231]])

In [74]:
data[data < 0]

array([-0.08774042, -0.02554547, -0.33386197, -0.92602617, -0.11427901,
       -1.04905211, -0.21951467, -0.04858503, -0.75535458, -0.58216024,
       -1.93996177, -0.64372841])

In [75]:
data[data < 0] = 0
print(data)

[[0.         1.37997841 0.50664524 0.        ]
 [0.08476618 0.         0.         0.        ]
 [0.94329292 0.         0.         0.        ]
 [0.17757912 1.2114927  1.12016855 0.18505731]
 [2.12477612 0.49703848 0.39375899 1.23850231]
 [0.31732413 0.         0.36194123 0.        ]
 [0.         1.97221378 0.62397917 0.        ]]


In [76]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.08476618, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.31732413, 0.        , 0.36194123, 0.        ],
       [0.        , 1.97221378, 0.62397917, 0.        ]])

# Fancy Indexing

In [77]:
arr = np.empty((8, 4))
for i in range(8):
        arr[i] = i

arr        

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [78]:
 arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [79]:
 arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [80]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [81]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [82]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [83]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [86]:
vector_a = np.array([[1, 4], [5, 6]]) 
vector_b = np.array([[2, 4], [5, 2]])
print(vector_a)
print()
print(vector_b)

[[1 4]
 [5 6]]

[[2 4]
 [5 2]]


In [87]:
product = np.dot(vector_a, vector_b) 
print("Dot Product  : \n", product) 

Dot Product  : 
 [[22 12]
 [40 32]]


In [91]:
product = np.dot(vector_b, vector_a) 
print("Dot Product  : \n", product) 

Dot Product  : 
 [[22 32]
 [15 32]]


In [89]:
arr = np.random.randn(6, 3)
arr

array([[ 0.425598  ,  1.06618898, -0.31356363],
       [ 0.67222141,  2.37823237, -1.42441381],
       [-0.52613001, -0.22434971,  0.83397167],
       [ 1.28489185, -0.27845588, -0.50908643],
       [ 1.67293016, -0.70499151, -1.01458246],
       [-0.97696425, -0.76801647, -0.36017751]])

In [94]:
arr.T

array([[ 0.425598  ,  0.67222141, -0.52613001,  1.28489185,  1.67293016,
        -0.97696425],
       [ 1.06618898,  2.37823237, -0.22434971, -0.27845588, -0.70499151,
        -0.76801647],
       [-0.31356363, -1.42441381,  0.83397167, -0.50908643, -1.01458246,
        -0.36017751]])

In [90]:
np.dot(arr.T, arr)

array([[ 6.3139296 ,  1.38364112, -3.52931709],
       [ 1.38364112,  8.00748096, -2.77535404],
       [-3.52931709, -2.77535404,  4.24106001]])

In [95]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [96]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [97]:
arr.transpose((0, 1, 2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [99]:
arr.transpose((1, 2, 0))

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [100]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [101]:
arr.transpose()

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [102]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [105]:
arr.swapaxes(2, 1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions: Fast Element-Wise Array Functions

In [106]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [108]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [109]:
x = np.random.randn(8)
x

array([ 0.68960127,  0.23837122,  0.10774672, -0.00880207, -0.82137665,
       -0.26208844, -0.96299877, -0.34904811])

In [110]:
y = np.random.randn(8)
y

array([ 0.06433996,  0.32279815, -1.079718  ,  1.57572519, -0.39062882,
        0.7547646 ,  0.83140966,  0.07889216])

In [111]:
np.maximum(x, y)

array([ 0.68960127,  0.32279815,  0.10774672,  1.57572519, -0.39062882,
        0.7547646 ,  0.83140966,  0.07889216])

In [134]:
arr = np.random.randn(7) * 5
arr

array([-5.37905959,  7.62232905,  3.45679937, -0.78534743, -7.15202556,
       11.29816451, -4.77667607])

In [135]:
remainder, whole_part = np.modf(arr)

In [136]:
remainder

array([-0.37905959,  0.62232905,  0.45679937, -0.78534743, -0.15202556,
        0.29816451, -0.77667607])

In [137]:
whole_part

array([-5.,  7.,  3., -0., -7., 11., -4.])

In [138]:
arr

array([-5.37905959,  7.62232905,  3.45679937, -0.78534743, -7.15202556,
       11.29816451, -4.77667607])

In [139]:
np.sqrt(arr)

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.76085658, 1.85924699,        nan,        nan,
       3.36127424,        nan])

In [140]:
arr

array([-5.37905959,  7.62232905,  3.45679937, -0.78534743, -7.15202556,
       11.29816451, -4.77667607])

In [141]:
arr1 = np.empty(7)

In [142]:
np.sqrt(arr,arr1)

C:\Users\Owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 2.76085658, 1.85924699,        nan,        nan,
       3.36127424,        nan])

In [143]:
arr

array([-5.37905959,  7.62232905,  3.45679937, -0.78534743, -7.15202556,
       11.29816451, -4.77667607])

In [144]:
arr1

array([       nan, 2.76085658, 1.85924699,        nan,        nan,
       3.36127424,        nan])

# Mathematical and Statistical Methods

In [145]:
arr = np.random.randn(5, 4)

In [146]:
arr

array([[ 0.90088359, -3.14808413, -0.86100401, -1.33650032],
       [ 0.37720863,  0.75529367, -0.51318379,  1.1219697 ],
       [-1.28121574, -2.76912033,  0.62835612, -2.37268214],
       [-0.23587748,  0.75711405, -2.41106308,  0.0275648 ],
       [ 0.11842431, -0.82539437,  1.73285176, -1.34211934]])

In [147]:
arr.mean()

-0.5338289048944136

In [148]:
arr.sum()

-10.676578097888271

In [149]:
np.mean(arr)

-0.5338289048944136

In [150]:
arr.mean()

-0.5338289048944136

In [151]:
arr.mean(axis=1)

array([-1.11117622,  0.43532205, -1.44866552, -0.46556543, -0.07905941])

In [152]:
arr.mean(axis=0)

array([-0.02411534, -1.04603822, -0.2848086 , -0.78035346])

In [153]:
 arr.sum(axis=0)

array([-0.12057668, -5.23019111, -1.42404301, -3.9017673 ])

In [154]:
arr.sum(0)

array([-0.12057668, -5.23019111, -1.42404301, -3.9017673 ])

In [155]:
arr.sum(1)

array([-4.44470486,  1.74128821, -5.79466208, -1.86226171, -0.31623765])

In [156]:
arr.cumsum()

array([  0.90088359,  -2.24720053,  -3.10820454,  -4.44470486,
        -4.06749623,  -3.31220256,  -3.82538636,  -2.70341666,
        -3.98463239,  -6.75375272,  -6.1253966 ,  -8.49807874,
        -8.73395622,  -7.97684218, -10.38790525, -10.36034045,
       -10.24191614, -11.06731051,  -9.33445876, -10.6765781 ])

In [157]:
arr

array([[ 0.90088359, -3.14808413, -0.86100401, -1.33650032],
       [ 0.37720863,  0.75529367, -0.51318379,  1.1219697 ],
       [-1.28121574, -2.76912033,  0.62835612, -2.37268214],
       [-0.23587748,  0.75711405, -2.41106308,  0.0275648 ],
       [ 0.11842431, -0.82539437,  1.73285176, -1.34211934]])

In [158]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [159]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [160]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [161]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [162]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [163]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [164]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]], dtype=int32)

In [165]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [166]:
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

In [171]:
arr = arr.reshape((1,9))

In [172]:
arr

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [173]:
arr.ndim

2

In [187]:
a = np.array([1,2,3,4,5,6,7,8])

In [188]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [189]:
a.ndim

1

In [190]:
a.shape

(8,)

In [191]:
a = a.reshape((2,2,2))

In [192]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [193]:
a.ndim

3

In [194]:
a = a.reshape((4,2)) 

In [195]:
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [196]:
a.ndim

2

In [197]:
a = a.reshape((8,1))

In [198]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [199]:
a = a.reshape((1,8))

In [200]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [201]:
a.ndim

2

In [207]:
a = a.reshape((8))

In [208]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [209]:
a.ndim

1

In [210]:
a.shape

(8,)

In [211]:
a = np.arange(8).reshape((2,2,2))

In [212]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [213]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [214]:
arr = np.random.randn(100)

In [217]:
arr

array([-0.07892158,  0.99670567, -0.57511442,  0.13857006,  0.67923439,
        0.51371882,  0.25165379,  0.63104755,  0.54271782, -0.51288877,
       -0.45541925, -1.42550445,  1.28362153,  0.45823638,  1.38028947,
        0.23426962,  0.41838474, -0.08707677, -0.12645619, -0.27123247,
       -1.40726031,  0.26767784, -0.97965159,  0.28039809, -0.40228207,
       -1.42094029,  1.17000302, -0.21179311,  0.14653918, -0.06839585,
       -1.69847233, -0.24230302,  0.02394893,  0.76210877,  1.38878766,
       -0.7918979 , -1.76180424,  0.78317227, -1.24388567, -0.45981565,
       -0.87434788, -0.32733882,  1.41501403,  0.81455273,  0.3749262 ,
        1.22259064,  0.00816474,  0.11916412, -0.87883141,  1.55195847,
        0.2783557 ,  0.78047409,  0.85716226, -0.09661188,  1.10842217,
       -1.1057293 ,  0.95012492, -0.12924191,  1.38759062, -1.92276218,
        0.42273159, -0.39626546, -0.14469147, -1.16667157,  0.31428347,
       -0.9384142 , -1.74068065,  0.44091525, -1.70723449,  0.05

In [216]:
(arr > 0).sum()

51

In [218]:
bools = np.array([False, False, True, False])

In [219]:
bool

bool

In [231]:
bools.any()

True

# Sorting

In [232]:
arr = np.random.randn(6)

In [233]:
arr

array([ 0.1113608 ,  0.50758747, -0.23250792, -0.33341356, -0.40056283,
        0.06401867])

In [234]:
arr.sort()

In [235]:
arr

array([-0.40056283, -0.33341356, -0.23250792,  0.06401867,  0.1113608 ,
        0.50758747])

In [236]:
arr = np.random.randn(5, 3)
arr

array([[ 0.0156819 ,  0.05412192,  0.00597391],
       [ 0.31182834, -1.91087149,  0.10717543],
       [-1.05044706, -0.3208261 , -1.56374565],
       [ 1.76766288, -0.33622628, -1.04293164],
       [-0.46243221, -0.04558601,  0.02035122]])

In [237]:
arr.sort(1)

In [238]:
arr

array([[ 0.00597391,  0.0156819 ,  0.05412192],
       [-1.91087149,  0.10717543,  0.31182834],
       [-1.56374565, -1.05044706, -0.3208261 ],
       [-1.04293164, -0.33622628,  1.76766288],
       [-0.46243221, -0.04558601,  0.02035122]])

In [239]:
large_arr = np.random.randn(1000)
large_arr

array([ 1.69328000e-01,  5.43485324e-01,  4.59540501e-01, -1.04724591e-01,
       -9.86473296e-01, -2.36969696e-01, -9.50312786e-02, -3.84374909e-01,
       -8.74241130e-02,  1.02668394e+00, -2.54520226e-01,  2.76627455e+00,
       -5.87380059e-01,  2.62119608e-02, -1.28084682e+00, -8.42173717e-02,
       -1.08953972e+00,  3.18133016e-01,  5.30201393e-01, -1.24712892e+00,
       -1.98420177e+00, -1.55191893e+00, -1.51064128e+00, -1.93425265e+00,
       -1.71706830e+00, -5.62410477e-01,  5.44902366e-01,  2.52778645e-01,
       -9.17572923e-01, -4.35125917e-01, -1.63624304e+00, -3.61883708e-01,
        1.31542861e+00, -1.58844790e+00,  3.19709581e-01, -1.13030445e-01,
       -9.81780958e-02,  2.46673904e+00,  4.53678934e-01, -1.26469263e+00,
        9.66431611e-01,  8.45045931e-01,  2.41171702e+00,  8.45072929e-01,
        3.54318164e-01,  1.44458591e+00, -7.52211343e-02, -4.88682732e-01,
       -5.82916613e-01, -1.92611670e-03,  2.26920339e-01,  7.65970303e-01,
       -1.51254475e+00, -

In [240]:
large_arr.sort()

In [241]:
large_arr

array([-2.90310090e+00, -2.86931567e+00, -2.70996719e+00, -2.67655345e+00,
       -2.45602912e+00, -2.45567367e+00, -2.42088841e+00, -2.35788020e+00,
       -2.28708245e+00, -2.21086416e+00, -2.19148442e+00, -2.16352616e+00,
       -2.05689478e+00, -2.00332076e+00, -1.98420177e+00, -1.93425265e+00,
       -1.92095908e+00, -1.92037159e+00, -1.91759843e+00, -1.90139760e+00,
       -1.88264056e+00, -1.86924319e+00, -1.86890468e+00, -1.85605961e+00,
       -1.83723287e+00, -1.82927283e+00, -1.81722391e+00, -1.81681136e+00,
       -1.73188802e+00, -1.71706830e+00, -1.71561700e+00, -1.70487372e+00,
       -1.69651314e+00, -1.68956277e+00, -1.67740451e+00, -1.64078756e+00,
       -1.63624304e+00, -1.63469129e+00, -1.62511763e+00, -1.62168214e+00,
       -1.58844790e+00, -1.57545729e+00, -1.56765577e+00, -1.56464861e+00,
       -1.56405425e+00, -1.55419332e+00, -1.55191893e+00, -1.51638162e+00,
       -1.51254475e+00, -1.51064128e+00, -1.50901155e+00, -1.50442199e+00,
       -1.47285815e+00, -

In [243]:
large_arr[int(0.05 * len(large_arr))] #5th percent number element

-1.5090115464526022