# numpy.arange()
NumPy-based algorithms are generally 10 to 100 times faster (or more) than their
pure Python counterparts and use significantly less memory

In [2]:
import numpy as np
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [3]:
# Python Programming illustrating 
# numpy.arange method 
  
import numpy as np
  
print("A\n", np.arange(4).reshape(2, 2), "\n") 
  
print("A\n", np.arange(4, 10), "\n") 
  
print("A\n", np.arange(4, 20, 3), "\n") 

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



# numpy.reshape()

In [4]:
# Python Program illustrating 
# numpy.reshape() method 
  
import numpy as np 
  
array = np.arange(8) 
print("Original array : \n", array) 
  
# shape array with 2 rows and 4 columns 
array = np.arange(8).reshape(2, 4) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 
  
# shape array with 2 rows and 4 columns 
array = np.arange(8).reshape(4 ,2) 
print("\narray reshaped with 2 rows and 4 columns : \n", array) 
  
# Constructs 3D array 
array = np.arange(8).reshape(2, 2, 2) 
print("\nOriginal array reshaped to 3D : \n", array) 

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [5]:
%time for _ in range(10): my_arr2 = array * 2

Wall time: 0 ns


# numpy.random.randn()

### randomly constructing 1D array

In [6]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 1D Array 
array = np.random.randn(5) 
print("1D Array filled with random values : \n", array); 


1D Array filled with random values : 
 [ 0.91745422  0.21910724  0.5240872  -0.94877639  0.20094091]


### randomly constructing 2D array

In [7]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 2D Array    
array = np.random.randn(3, 4) 
print("2D Array filled with random values : \n", array);

2D Array filled with random values : 
 [[-1.14891291  0.06614862 -1.28743286 -1.75775407]
 [-0.37266341 -1.48232792  0.0020795  -0.23538986]
 [ 1.03283087  0.48657581  0.16008567  0.80989888]]


### randomly constructing 3D array

In [8]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 3D Array      
array = np.random.randn(2, 2 ,2) 
print("3D Array filled with random values : \n", array);

3D Array filled with random values : 
 [[[-0.82457764  0.23461268]
  [-0.34269206  1.4908616 ]]

 [[ 1.0995562   0.70348608]
  [ 1.1394488   0.67813938]]]


In [9]:
# Python Program illustrating 
# numpy.random.randn() method 
   
import numpy as np 
   
# 3D Array      
array = np.random.randn(2, 2 ,2) 
print("3D Array filled with random values : \n", array); 
       
# Multiplying values with 3 
print("\nArray * 3 : \n", array *3) 

# Multiplying values with 3 + 2
print("\nArray * 3 + 2 : \n", array *3 + 2) 
  
# Or we cab directly do so by  
array = np.random.randn(2, 2 ,2) * 3 + 2
print("\nArray * 3 + 2 : \n", array); 


3D Array filled with random values : 
 [[[-0.57155833 -1.22082665]
  [-0.80934142 -1.08535306]]

 [[ 0.25952855  0.53611308]
  [-0.21942844 -0.81196417]]]

Array * 3 : 
 [[[-1.71467499 -3.66247996]
  [-2.42802427 -3.25605919]]

 [[ 0.77858566  1.60833923]
  [-0.65828533 -2.43589251]]]

Array * 3 + 2 : 
 [[[ 0.28532501 -1.66247996]
  [-0.42802427 -1.25605919]]

 [[ 2.77858566  3.60833923]
  [ 1.34171467 -0.43589251]]]

Array * 3 + 2 : 
 [[[-1.84251636  3.3268681 ]
  [ 1.92814435 -0.15465635]]

 [[ 2.31691493  0.86615859]
  [ 4.44628175  1.38693769]]]


# Creating ndarrays

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
#print(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [11]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# Python program for
# Creation of Arrays
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


### .ndim

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.ndim)

2


### .shape

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.shape)

(2, 4)


### .dtype

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2.dtype)

int32


# numpy.zeros()

In [16]:
arr =  np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
arr = np.zeros((3, 6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
import numpy as geek 
  
b = np.zeros(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.zeros([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.zeros([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Python Program illustrating 
# numpy.zeros method 
  
import numpy as np 
  
# manipulation with data-types 
b = np.zeros(2, dtype=[('x', 'float'), ('y', 'int'),("z","complex")]) 
print(b)

[(0., 0, 0.+0.j) (0., 0, 0.+0.j)]


# numpy.empty()
It’s not safe to assume that np.empty will return an array of all
zeros. In some cases, it may return uninitialized “garbage” values.

In [20]:
# Python Programming illustrating 
# numpy.empty method 
  
import numpy as np 
  
b = np.empty(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.empty([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.empty([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# numpy.ones()

In [21]:
# numpy.ones method 
  
import numpy as np
  
b = np.ones(2, dtype = int) 
print("Matrix b : \n", b) 
  
a = np.ones([2, 2], dtype = int) 
print("\nMatrix a : \n", a) 
  
c = np.ones([3, 3]) 
print("\nMatrix c : \n", c) 

Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# numpy.eye()

In [22]:
import numpy as np 
  
# 2x2 matrix with 1's on main diagnol 
b = np.eye(2, dtype = float) 
print("Matrix b : \n", b) 
  
# matrix with R=4 C=5 and 1 on diagnol 
# below main diagnol 
a = np.eye(4, 5, k = -1) 
print("\nMatrix a : \n", a)

Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# numpy.identity() in Python

In [23]:
import numpy as np 
  
# 2x2 matrix with 1's on main diagnol 
b = np.identity(2, dtype = float) 
print("Matrix b : \n", b) 
  
  
a = np.identity(4) 
print("\nMatrix a : \n", a) 

Matrix b : 
 [[1. 0.]
 [0. 1.]]

Matrix a : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# NumPy data types

In [24]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int32


In [25]:
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

float64


In [26]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)
print(arr)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


# Arithmetic with NumPy Arrays

In [27]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [28]:
print(arr * arr)

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [29]:
print(arr - arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
print(1 / arr)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [32]:
print(arr ** 0.5)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [33]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [34]:
print( arr2 > arr)

[[False  True False]
 [ True False  True]]


In [35]:
print(arr > arr2)

[[ True False  True]
 [False  True False]]


# Basic Indexing and Slicing